version: "3.9"

services:
  javanadpythondb:
    image: postgres:15
    container_name: javanadpythondb
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mydb" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  spring:
    build: ./java
    container_name: spring
    ports:
      - "5002:5002"
    depends_on:
      javanadpythondb:
        condition: service_healthy

  fastapi:
    build: ./python
    container_name: fastapi
    depends_on:
      javanadpythondb:
        condition: service_healthy
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb

  debug:
    image: alpine:latest
    container_name: debug
    command: sh -c "apk add --no-cache curl iputils && sleep infinity"

volumes:
  pgdata:

networks:
  javapython: